const cities = [
   { name: 'Cairo',          fee: 90},
  { name: 'Giza',           fee: 90},
  { name: 'Alexandria',     fee: 120  },
  { name: 'Shubra El Kheima', fee:90},
  { name: 'Port Said',      fee: 120  },
  { name: 'Suez',           fee: 120},
  { name: 'Luxor',          fee: 140 },
  { name: 'Mansoura',       fee: 120  },
  { name: 'El Mahalla El Kubra', fee: 120 },
  { name: 'Tanta',          fee: 120  },
  { name: 'Asyut',          fee: 140 },
  { name: 'Ismailia',       fee: 120  },
  { name: 'Fayyum',         fee: 120  },
  { name: 'Zagazig',        fee: 120  },
  { name: 'Damietta',       fee: 120  },
  { name: 'Aswan',          fee: 140 },
  { name: 'Minya',          fee: 140},
  { name: 'qalyobia',          fee: 90 },
  { name: 'qalyob',          fee: 90 },
  { name: 'Damanhour',      fee: 120  },
  { name: 'Beni Suef',      fee: 140},
  { name: 'Hurghada',       fee: 160},
  { name: 'Sharm El Sheikh', fee: 160},
  { name: 'Sohag',          fee: 140},
  { name: 'Qena',           fee: 140 },
  { name: 'Shibin El Kom',  fee: 120  },
  { name: 'Banha',          fee: 90},
  { name: '10th of Ramadan', fee: 120 },
  { name: 'Arish',          fee: 160},
  { name: 'Kafr El Sheikh',  fee: 120 },
  { name: 'Other',          fee: 160},
];
module.exports = cities;
